let conteo=0;

function myFunction(){
conteo=conteo++;
    if(conteo%2==0){
        document.getElementById("identificador").innerHTML="Un emprendedor (emprendedora, en femenino) es una persona que identifica una oportunidad y que, conociendo los riesgos, emprende la acción de organizar los recursos necesarios para crear o fundar una empresa o negocio(individual o colectivamente), con la finalidad de aprovechar dicha oportunidad, obteniendo una respectiva ganancia.";
         }else{
        document.getElementById("demo").innerHTML="Entrepreneur is a a person who sets up a business or businesses, taking on financial risks in the hope of profit."
         }
         }